-- Run this in Supabase: SQL Editor → New query → Run.
-- Same columns as the former SQLite `analyses` table (Postgres types).

CREATE TABLE IF NOT EXISTS public.analyses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    title text NOT NULL,
    feedback_text text NOT NULL,
    results_json text NOT NULL
);

COMMENT ON TABLE public.analyses IS 'Stored feedback analyzer runs (migrated from SQLite schema).';

ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon to read analyses" ON public.analyses;
CREATE POLICY "Allow anon to read analyses"
    ON public.analyses
    FOR SELECT
    TO anon
    USING (true);

DROP POLICY IF EXISTS "Allow anon to insert analyses" ON public.analyses;
CREATE POLICY "Allow anon to insert analyses"
    ON public.analyses
    FOR INSERT
    TO anon
    WITH CHECK (true);
